name: Hex

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Setup rebar3 hex
        run: |
          mkdir -p ~/.config/rebar3/
          echo "{plugins, [rebar3_hex]}." > ~/.config/rebar3/rebar.config

      - name: Publish to hex.pm
        run: DIAGNOSTIC=1 rebar3 hex publish --repo hexpm --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}

      - name: Check crash dump
        run: head rebar3.crashdump
